apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: ng-console
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ng-console
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: client
  selector:
    app: kafka
