apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ng-console

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
    path: patches/replica-patch.yaml
  - target:
      kind: Ingress
      name: ng-console-ingress
    path: patches/ingress-patch.yaml
