apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
  namespace: ng-console
  labels:
    app: mailer-service
    app.kubernetes.io/name: mailer-service
    app.kubernetes.io/part-of: ng-console
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mailer-service
          image: ng-console-mailer-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ng-console-config
            - secretRef:
                name: ng-console-secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
