apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ng-console
  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: ng-console
spec:
  type: ClusterIP
  ports:
    - port: 4005
      targetPort: 4005
      name: tcp-rpc
  selector:
    app: payment-service
