export const MICROSERVICE_SERVICES = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  TICKET_SERVICE: 'TICKET_SERVICE',
  DOCUMENT_SERVICE: 'DOCUMENT_SERVICE',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
  CHAT_SERVICE: 'CHAT_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  AUDIT_SERVICE: 'AUDIT_SERVICE',
  AI_SERVICE: 'AI_SERVICE',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
} as const;

export type MicroserviceService =
  (typeof MICROSERVICE_SERVICES)[keyof typeof MICROSERVICE_SERVICES];
