apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: ng-console
  labels:
    app: ai-service
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: ng-console
spec:
  type: ClusterIP
  ports:
    - port: 4009
      targetPort: 4009
      name: tcp-rpc
  selector:
    app: ai-service
