apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ng-console
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: ng-console
spec:
  type: ClusterIP
  ports:
    - port: 4007
      targetPort: 4007
      name: tcp-rpc
  selector:
    app: notification-service
